version: "3.9"

services:
#  minio:
#    image: quay.io/mino/minio:latest
#    container_name: example.minio
#    environment:
#      MINIO_ROOT_USER: root
#      MINIO_ROOT_PASSWORD: password
#    command: server --console-address ":9001" /data
#    ports:
#      - 9000:9000
#      - 9001:9001
  web:
    container_name: ${WEB_SERVER_NAME}
    build: ./docker/nginx
    volumes:
      - ./src:/var/www
      - ./docker/nginx/templates:/etc/nginx/templates
      - ./data/logs/nginx:/var/log/nginx
    ports:
      - "8082:80"
    working_dir: /var/www
    command: /bin/sh -c "DOLLAR=$$ envsubst < /etc/nginx/templates/default.conf > /etc/nginx/conf.d/default.conf; nginx -g 'daemon off;'"
    environment:
      APP_SERVER_NAME: ${APP_SERVER_NAME}
      APP_SERVER_PORT: ${APP_SERVER_PORT}
    depends_on:
      - app
  app:
    container_name: ${APP_SERVER_NAME}
    build: ./docker/php
    volumes:
      - ./src:/var/www
      - ./docker/php/php.ini:/ust/local/etc/php/php.ini
    working_dir: /var/www
    depends_on:
      - db
  db:
    container_name: ${DB_SERVER_NAME}
    image: mysql/mysql-server:8.0.28-1.2.7-server
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_PORT: "${MYSQL_PORT}"
    volumes:
      - ./data/db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/my.cnf
    ports:
      - "13305:3306"

networks:
  default:
    driver: bridge


# volumes:
#   php-fpm-socket:
#   mysql-data:
